/* eslint-disable @typescript-eslint/no-require-imports */

import type { ImageSourcePropType } from "react-native";

export const generatedTemplateIds = [
  "wedding-anime-blossom",
  "wedding-anime-moonlight",
  "wedding-peach-morning",
  "wedding-sage-garden",
  "wedding-lilac-veil",
  "wedding-champagne-ribbon",
  "wedding-blue-hydrangea",
  "wedding-coral-sunset",
  "wedding-mint-terrace",
  "wedding-paper-flower",
  "dol-teddy-pastel",
  "dol-cloud-moon",
  "dol-candy-balloon",
  "dol-picnic-bear",
  "dol-dino-sprout",
  "dol-peach-bunny",
  "dol-ocean-whale",
  "dol-rainbow-milk",
  "dol-little-astronaut",
  "dol-garden-cake",
  "hwangap-royal-bojagi",
  "hwangap-jade-crane",
  "hwangap-champagne-peony",
  "hwangap-coral-silk",
  "hwangap-sky-garden",
  "hwangap-lemon-hanok",
  "hwangap-mint-orchid",
  "hwangap-rose-dinner",
  "hwangap-pearl-ribbon",
  "hwangap-spring-bamboo",
  "house-cozy-sage",
  "house-city-night",
  "house-sunny-kitchen",
  "house-plant-loft",
  "house-terrace-brunch",
  "house-cream-sofa",
  "house-blue-apartment",
  "house-yellow-door",
  "house-picnic-table",
  "house-rooftop-sunset",
] as const;

export type GeneratedTemplateId = (typeof generatedTemplateIds)[number];

export const generatedTemplatePreviewSource: Record<GeneratedTemplateId, ImageSourcePropType> = {
  "wedding-anime-blossom": require("../assets/template-previews/custom/generated-2026/wedding/wedding-anime-blossom.png"),
  "wedding-anime-moonlight": require("../assets/template-previews/custom/generated-2026/wedding/wedding-anime-moonlight.png"),
  "wedding-peach-morning": require("../assets/template-previews/custom/generated-2026/wedding/wedding-peach-morning.png"),
  "wedding-sage-garden": require("../assets/template-previews/custom/generated-2026/wedding/wedding-sage-garden.png"),
  "wedding-lilac-veil": require("../assets/template-previews/custom/generated-2026/wedding/wedding-lilac-veil.png"),
  "wedding-champagne-ribbon": require("../assets/template-previews/custom/generated-2026/wedding/wedding-champagne-ribbon.png"),
  "wedding-blue-hydrangea": require("../assets/template-previews/custom/generated-2026/wedding/wedding-blue-hydrangea.png"),
  "wedding-coral-sunset": require("../assets/template-previews/custom/generated-2026/wedding/wedding-coral-sunset.png"),
  "wedding-mint-terrace": require("../assets/template-previews/custom/generated-2026/wedding/wedding-mint-terrace.png"),
  "wedding-paper-flower": require("../assets/template-previews/custom/generated-2026/wedding/wedding-paper-flower.png"),
  "dol-teddy-pastel": require("../assets/template-previews/custom/generated-2026/dol/dol-teddy-pastel.png"),
  "dol-cloud-moon": require("../assets/template-previews/custom/generated-2026/dol/dol-cloud-moon.png"),
  "dol-candy-balloon": require("../assets/template-previews/custom/generated-2026/dol/dol-candy-balloon.png"),
  "dol-picnic-bear": require("../assets/template-previews/custom/generated-2026/dol/dol-picnic-bear.png"),
  "dol-dino-sprout": require("../assets/template-previews/custom/generated-2026/dol/dol-dino-sprout.png"),
  "dol-peach-bunny": require("../assets/template-previews/custom/generated-2026/dol/dol-peach-bunny.png"),
  "dol-ocean-whale": require("../assets/template-previews/custom/generated-2026/dol/dol-ocean-whale.png"),
  "dol-rainbow-milk": require("../assets/template-previews/custom/generated-2026/dol/dol-rainbow-milk.png"),
  "dol-little-astronaut": require("../assets/template-previews/custom/generated-2026/dol/dol-little-astronaut.png"),
  "dol-garden-cake": require("../assets/template-previews/custom/generated-2026/dol/dol-garden-cake.png"),
  "hwangap-royal-bojagi": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-royal-bojagi.png"),
  "hwangap-jade-crane": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-jade-crane.png"),
  "hwangap-champagne-peony": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-champagne-peony.png"),
  "hwangap-coral-silk": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-coral-silk.png"),
  "hwangap-sky-garden": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-sky-garden.png"),
  "hwangap-lemon-hanok": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-lemon-hanok.png"),
  "hwangap-mint-orchid": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-mint-orchid.png"),
  "hwangap-rose-dinner": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-rose-dinner.png"),
  "hwangap-pearl-ribbon": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-pearl-ribbon.png"),
  "hwangap-spring-bamboo": require("../assets/template-previews/custom/generated-2026/hwangap/hwangap-spring-bamboo.png"),
  "house-cozy-sage": require("../assets/template-previews/custom/generated-2026/housewarming/house-cozy-sage.png"),
  "house-city-night": require("../assets/template-previews/custom/generated-2026/housewarming/house-city-night.png"),
  "house-sunny-kitchen": require("../assets/template-previews/custom/generated-2026/housewarming/house-sunny-kitchen.png"),
  "house-plant-loft": require("../assets/template-previews/custom/generated-2026/housewarming/house-plant-loft.png"),
  "house-terrace-brunch": require("../assets/template-previews/custom/generated-2026/housewarming/house-terrace-brunch.png"),
  "house-cream-sofa": require("../assets/template-previews/custom/generated-2026/housewarming/house-cream-sofa.png"),
  "house-blue-apartment": require("../assets/template-previews/custom/generated-2026/housewarming/house-blue-apartment.png"),
  "house-yellow-door": require("../assets/template-previews/custom/generated-2026/housewarming/house-yellow-door.png"),
  "house-picnic-table": require("../assets/template-previews/custom/generated-2026/housewarming/house-picnic-table.png"),
  "house-rooftop-sunset": require("../assets/template-previews/custom/generated-2026/housewarming/house-rooftop-sunset.png"),
};

export const generatedTemplateCanvasSource: Record<GeneratedTemplateId, ImageSourcePropType> = generatedTemplatePreviewSource;

