/* eslint-disable @typescript-eslint/no-require-imports */

import type { ImageSourcePropType } from "react-native";
import { bundledTemplateCanvasIds, bundledTemplatePreviewIds } from "./template-preview-manifest";

type BundledTemplatePreviewId = (typeof bundledTemplatePreviewIds)[number];
type BundledTemplateCanvasId = (typeof bundledTemplateCanvasIds)[number];

const bundledTemplateCanvasSource: Record<BundledTemplateCanvasId, ImageSourcePropType> = {
  "wedding-classic": require("../assets/template-previews/custom/wedding/wedding-01.jpeg"),
  "wedding-modern": require("../assets/template-previews/custom/wedding/wedding-02.jpeg"),
  "wedding-floral": require("../assets/template-previews/custom/wedding/wedding-03.jpeg"),
  "wedding-minimal": require("../assets/template-previews/custom/wedding/wedding-04.jpeg"),
  "wedding-nature": require("../assets/template-previews/custom/wedding/wedding-05.jpeg"),
  "wedding-rose-gold": require("../assets/template-previews/custom/wedding/wedding-06.jpeg"),
  "wedding-photo-minimal": require("../assets/template-previews/custom/wedding/wedding-07.jpg"),
  "wedding-blush-petal": require("../assets/template-previews/custom/wedding/wedding-08.jpg"),
  "wedding-traditional-knot": require("../assets/template-previews/custom/wedding/wedding-09.jpg"),
  "wedding-envelope-photo": require("../assets/template-previews/custom/wedding/wedding-10.jpg"),
  "wedding-gold-botanical": require("../assets/template-previews/custom/wedding/wedding-11.jpg"),
  "wedding-illustration-curtain": require("../assets/template-previews/custom/wedding/wedding-12.jpg"),
  "wedding-botanical-vertical": require("../assets/template-previews/custom/wedding/wedding-13.jpg"),
  "wedding-photo-overlay": require("../assets/template-previews/custom/wedding/wedding-14.jpg"),
  "wedding-photo-hero": require("../assets/template-previews/custom/wedding/wedding-15.jpg"),
  "wedding-green-arch": require("../assets/template-previews/custom/wedding/wedding-16.jpg"),
  "wedding-anime-textspace-01": require("../assets/template-previews/custom/wedding/wedding-17.jpg"),
  "wedding-anime-textspace-02": require("../assets/template-previews/custom/wedding/wedding-18.jpg"),
  "wedding-anime-textspace-03": require("../assets/template-previews/custom/wedding/wedding-19.jpg"),
  "wedding-anime-textspace-04": require("../assets/template-previews/custom/wedding/wedding-20.jpg"),
  "wedding-anime-textspace-05": require("../assets/template-previews/custom/wedding/wedding-21.jpg"),
  "wedding-anime-textspace-06": require("../assets/template-previews/custom/wedding/wedding-22.jpg"),
  "wedding-anime-textspace-07": require("../assets/template-previews/custom/wedding/wedding-23.jpg"),
  "wedding-anime-textspace-08": require("../assets/template-previews/custom/wedding/wedding-24.jpg"),
  "wedding-anime-textspace-09": require("../assets/template-previews/custom/wedding/wedding-25.jpg"),
  "wedding-anime-textspace-10": require("../assets/template-previews/custom/wedding/wedding-26.jpg"),
  "dol-cute": require("../assets/template-previews/custom/dol/dol-card-01.jpeg"),
  "dol-pastel": require("../assets/template-previews/custom/dol/dol-card-02.jpeg"),
  "dol-blue": require("../assets/template-previews/custom/dol/dol-card-03.jpeg"),
  "dol-nature": require("../assets/template-previews/custom/dol/dol-card-04.jpeg"),
  "dol-gold": require("../assets/template-previews/custom/dol/dol-cake-01.jpeg"),
  "hwangap-classic": require("../assets/template-previews/custom/hwangap/hwangap-01.jpeg"),
  "hwangap-modern": require("../assets/template-previews/custom/hwangap/hwangap-02.jpeg"),
  "hwangap-red": require("../assets/template-previews/custom/hwangap/hwangap-03.jpeg"),
  "hwangap-floral": require("../assets/template-previews/custom/hwangap/hwangap-04.jpeg"),
  "hwangap-hanja": require("../assets/template-previews/custom/hwangap/hwangap-05.jpeg"),
  "bridal-pink": require("../assets/template-previews/custom/bridal/bridal-01.jpeg"),
  "bridal-boho": require("../assets/template-previews/custom/bridal/bridal-02.jpeg"),
  "bridal-modern": require("../assets/template-previews/custom/bridal/bridal-03.jpeg"),
  "bridal-mint": require("../assets/template-previews/custom/bridal/bridal-04.jpeg"),
  "birthday-fun": require("../assets/template-previews/custom/birthday/birthday-01.jpeg"),
  "birthday-elegant": require("../assets/template-previews/custom/birthday/birthday-02.jpeg"),
  "birthday-kids": require("../assets/template-previews/custom/birthday/birthday-03.jpeg"),
  "house-warm": require("../assets/template-previews/custom/other/house-warm-v2.png"),
  "house-modern": require("../assets/template-previews/custom/other/house-modern.jpeg"),
  "baby-shower": require("../assets/template-previews/custom/other/baby-shower.jpeg"),
  "baby-pink": require("../assets/template-previews/custom/other/baby-pink-v2.png"),
  graduation: require("../assets/template-previews/custom/other/graduation-v2.png"),
  "graduation-warm": require("../assets/template-previews/custom/other/graduation-warm.jpeg"),
  business: require("../assets/template-previews/custom/other/business-v2.png"),
  "business-dark": require("../assets/template-previews/custom/other/business-dark.jpeg"),
  "wedding-anime-2026": require("../assets/template-previews/custom/anime-2026/wedding-anime-2026.jpg"),
  "dol-anime-2026": require("../assets/template-previews/custom/anime-2026/dol-anime-2026.jpg"),
  "hwangap-anime-2026": require("../assets/template-previews/custom/anime-2026/hwangap-anime-2026.jpg"),
  "bridal-anime-2026": require("../assets/template-previews/custom/anime-2026/bridal-anime-2026.jpg"),
  "birthday-anime-2026": require("../assets/template-previews/custom/anime-2026/birthday-anime-2026.jpg"),
  "housewarming-anime-2026": require("../assets/template-previews/custom/anime-2026/housewarming-anime-2026.jpg"),
  "baby-anime-2026": require("../assets/template-previews/custom/anime-2026/baby-anime-2026.jpg"),
  "graduation-anime-2026": require("../assets/template-previews/custom/anime-2026/graduation-anime-2026.jpg"),
  "business-anime-2026": require("../assets/template-previews/custom/anime-2026/business-anime-2026.jpg"),
  "wedding-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-01.jpg"),
  "wedding-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-02.jpg"),
  "wedding-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-03.jpg"),
  "wedding-barunson-anime-04": require("../assets/home-hero/wedding-04.png"),
  "wedding-barunson-anime-09": require("../assets/home-hero/wedding-09.png"),
  "wedding-barunson-anime-10": require("../assets/home-hero/wedding-10.png"),
  "dol-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-01.jpg"),
  "dol-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-02.jpg"),
  "dol-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-03.jpg"),
  "housewarming-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-01.jpg"),
  "housewarming-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-02.jpg"),
  "housewarming-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-03.jpg"),
  "hwangap-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-01.jpg"),
  "hwangap-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-02.jpg"),
  "hwangap-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-03.jpg"),
  "bridal-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/bridal-01.jpg"),
  "bridal-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/bridal-02.jpg"),
  "bridal-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/bridal-03.jpg"),
  "birthday-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-01.jpg"),
  "birthday-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-02.jpg"),
  "birthday-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-03.jpg"),
  "baby-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-01.jpg"),
  "baby-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-02.jpg"),
  "baby-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-03.jpg"),
  "graduation-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/graduation-01.jpg"),
  "graduation-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/graduation-02.jpg"),
  "graduation-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/graduation-03.jpg"),
  "business-barunson-anime-01": require("../assets/template-previews/custom/barunson-category-anime-2026/business-01.jpg"),
  "business-barunson-anime-02": require("../assets/template-previews/custom/barunson-category-anime-2026/business-02.jpg"),
  "business-barunson-anime-03": require("../assets/template-previews/custom/barunson-category-anime-2026/business-03.jpg"),
  "wedding-barunson-anime-25": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-25.png"),
  "wedding-barunson-anime-26": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-26.png"),
  "wedding-barunson-anime-27": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-27.png"),
  "wedding-barunson-anime-28": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-28.png"),
  "wedding-barunson-anime-29": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-29.png"),
  "wedding-barunson-anime-30": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-30.png"),
  "wedding-barunson-anime-31": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-31.png"),
  "wedding-barunson-anime-32": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-32.png"),
  "wedding-barunson-anime-33": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-33.png"),
  "wedding-barunson-anime-34": require("../assets/template-previews/custom/barunson-category-anime-2026/wedding-34.png"),
  "dol-barunson-anime-16": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-16.png"),
  "dol-barunson-anime-17": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-17.png"),
  "dol-barunson-anime-18": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-18.png"),
  "dol-barunson-anime-19": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-19.png"),
  "dol-barunson-anime-20": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-20.png"),
  "dol-barunson-anime-21": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-21.png"),
  "dol-barunson-anime-22": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-22.png"),
  "dol-barunson-anime-23": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-23.png"),
  "dol-barunson-anime-24": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-24.png"),
  "dol-barunson-anime-25": require("../assets/template-previews/custom/barunson-category-anime-2026/dol-25.png"),
  "birthday-barunson-anime-05": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-05.png"),
  "birthday-barunson-anime-06": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-06.png"),
  "birthday-barunson-anime-07": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-07.png"),
  "birthday-barunson-anime-08": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-08.png"),
  "birthday-barunson-anime-09": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-09.png"),
  "birthday-barunson-anime-10": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-10.png"),
  "birthday-barunson-anime-11": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-11.png"),
  "birthday-barunson-anime-12": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-12.png"),
  "birthday-barunson-anime-13": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-13.png"),
  "birthday-barunson-anime-14": require("../assets/template-previews/custom/barunson-category-anime-2026/birthday-14.png"),
  "baby-barunson-anime-05": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-05.png"),
  "baby-barunson-anime-06": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-06.png"),
  "baby-barunson-anime-07": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-07.png"),
  "baby-barunson-anime-08": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-08.png"),
  "baby-barunson-anime-09": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-09.png"),
  "baby-barunson-anime-10": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-10.png"),
  "baby-barunson-anime-11": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-11.png"),
  "baby-barunson-anime-12": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-12.png"),
  "baby-barunson-anime-13": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-13.png"),
  "baby-barunson-anime-14": require("../assets/template-previews/custom/barunson-category-anime-2026/baby-14.png"),
  "housewarming-barunson-anime-10": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-10.png"),
  "housewarming-barunson-anime-11": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-11.png"),
  "housewarming-barunson-anime-12": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-12.png"),
  "housewarming-barunson-anime-13": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-13.png"),
  "housewarming-barunson-anime-14": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-14.png"),
  "housewarming-barunson-anime-15": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-15.png"),
  "housewarming-barunson-anime-16": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-16.png"),
  "housewarming-barunson-anime-17": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-17.png"),
  "housewarming-barunson-anime-18": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-18.png"),
  "housewarming-barunson-anime-19": require("../assets/template-previews/custom/barunson-category-anime-2026/housewarming-19.png"),
  "hwangap-barunson-anime-08": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-08.png"),
  "hwangap-barunson-anime-09": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-09.png"),
  "hwangap-barunson-anime-10": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-10.png"),
  "hwangap-barunson-anime-11": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-11.png"),
  "hwangap-barunson-anime-12": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-12.png"),
  "hwangap-barunson-anime-13": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-13.png"),
  "hwangap-barunson-anime-14": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-14.png"),
  "hwangap-barunson-anime-15": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-15.png"),
  "hwangap-barunson-anime-16": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-16.png"),
  "hwangap-barunson-anime-17": require("../assets/template-previews/custom/barunson-category-anime-2026/hwangap-17.png")
};

export function hasBundledTemplatePreview(templateId: string): templateId is BundledTemplatePreviewId {
  return bundledTemplatePreviewIds.includes(templateId as BundledTemplatePreviewId);
}

export function getBundledTemplatePreviewSource(templateId: string) {
  if (!hasBundledTemplatePreview(templateId)) {
    return null;
  }

  return getBundledTemplateCanvasSource(templateId);
}

export function getBundledTemplateCanvasSource(templateId: string) {
  if (!bundledTemplateCanvasIds.includes(templateId as BundledTemplateCanvasId)) {
    return null;
  }

  return bundledTemplateCanvasSource[templateId as BundledTemplateCanvasId];
}
